name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2022-12-15
version: '10.0.0'
project: 'drupal'
datestamp: 1671126000
